apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    servicefor: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    servicefor: {{ .Release.Name }}-{{ .Chart.Name }}
  type: {{ .Values.service.type }}

